blank_issues_enabled: false
contact_links:
  - name: Support via Discord
    url: https://radarr.video/discord
    about: Chat with users and devs on support and setup related topics.
  - name: Support via Reddit
    url: https://reddit.com/r/radarr
    about: Discuss and search thru support topics.
